server:
  port: 8082
  servlet:
    session:
      timeout: 30m
    context-path: service
rsa:
  private:
    key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAJfxQ/K5YFFHoX83dJKW+zyL87aPYov1T4xsBeoGBPgx8mt0ng/yPKHZJtBn9JnyxFsHCyFEPNeECzz3y79sLz4WsJZYdB9kKi0q+ceHyU/VmfOCCbesnanKioG9a3Z8ibRqpULHYlpiURn+498PW2rVMKY9NjeBvpzuIoLBjd49AgMBAAECgYEAk0tD/41Nnf2+xUDRNTpAG5XgkN23Ps50a0BdC10CfEiPJTRL9lFyDcQhKG9eY89AIq5VT86C3LoY2uWtEsihkiIku7bBS2vvoBJtTiNg2spA5efAYp++M01sIwmA99v/+NHbRmpKUjo8cIYKx906jOTj/TcwfZ6aeDxb6gEkIQECQQDdXN49yjHPqXuieureQuw2mk4rQCvP5SJxM401/KA+J13L7f2PAbA01zzuzbg1DkaoD+178BYBeSwErKi1VRmRAkEAr7egVRZDd5ty+LPa71HBbj5Lm7bS7OI6vge76p9MPRhrJZLb6noc3r7inQ5gEjRX7thHkALJhG3mzX7JorCD7QJBAIWNpjg5aVwUsRcSeemnDsTSzB6kFMrVP7Z0l9nelP9q2NhUugoxxpHa2lRpoZ3BAzgag/mmnGA/LyOS2CavNUECQQCj9oN8gf7If9wDZ8g2IiKNXUGt9iXRdrP7mDnoD2bTZ5Krh+L/Y5zG2HWaucw5kHAw5c24+nDRyr9gJxu9XFptAkAFeiXnlWCDFgtbrXVZQNgSSyPEjbGjz1b84kJpq63rBa14MrpHEDTqurjgqvjSN9CFBlb7MkQAfsZhnF20qaFF
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hongdun.entity
logging:
  file: logs/hongdun.log
  pattern:
    console: "%d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
file:
  upload:
    path: /www/data/static/image/
    url: https://api.kidskeeper.cn/static/image/
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB