server:
  port: 8888
  servlet:
    session:
      timeout: 10s

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hongdun.entity
logging:
  file: logs/hongdun.log
  pattern:
    console: "%d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"